#pragma config(Motor,  motorA,          motorSensor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl)
#pragma config(Motor,  motorD,          motorRight,    tmotorEV3_Large, PIDControl)
#pragma config(Sensor, S2, ultrasonicSensor, sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TARGET_DISTANCE_SENSOR 90
#define SENSOR_MOTOR_SPEED 90
#define WALL_SENSOR_DISTANCE 150

#define TARGET_DISTANCE_FORWARD 500
#define TARGET_DISTANCE_TURN 215
#define MOTOR_SPEED 5

void MoveSensorClockwise(int target);
void MoveSensorDefault();
bool ScanForWall();
void CheckWallInDirection(int direction);
void MoveForward();
void TurnLeft();
void TurnRight();

task main()
{
    TurnLeft();
    sleep(1000);  // Pause between checks
}

// Turn the robot left
void TurnLeft() {
    nMotorEncoder[motorLeft] = 0;//reset the value of encoder B to zero
		nMotorEncoder[motorRight] = 0;//reset the value of encoder C to zero

		while(nMotorEncoder[motorRight] < TARGET_DISTANCE_TURN)//while encoderB is less than 720
		{
			motor[motorLeft] = -MOTOR_SPEED;//turn on motorB at 50% power
			motor[motorRight] = MOTOR_SPEED;//turn on motorC at 50% power
		}

		motor[motorLeft] = 0; //Turn off motorB
		motor[motorRight] = 0; //Turn off motorC
}

// Turn the robot right
void TurnRight() {
    nMotorEncoder[motorLeft] = 0;//reset the value of encoder B to zero
		nMotorEncoder[motorRight] = 0;//reset the value of encoder C to zero

		while(nMotorEncoder[motorLeft] < TARGET_DISTANCE_TURN)//while encoderB is less than 720
		{
			motor[motorLeft] = MOTOR_SPEED;//turn on motorB at 50% power
			motor[motorRight] = -MOTOR_SPEED;//turn on motorC at 50% power
		}

		motor[motorLeft] = 0; //Turn off motorB
		motor[motorRight] = 0; //Turn off motorC
}
