#pragma config(Motor,  motorA,          motorSensor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl)
#pragma config(Motor,  motorD,          motorRight,    tmotorEV3_Large, PIDControl)
#pragma config(Sensor, S2, ultrasonicSensor, sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TARGET_DISTANCE_SENSOR 90  // Example target distance in encoder counts

void MoveSensorClockwise(int target);
void MoveSensorDefault();
bool ScanForWall();

task main()
{
	  while(true){
		  nMotorEncoder[motorSensor] = 0;
			if (ScanForWall()) {
				displayCenteredTextLine(5,"Wall Found Left: %d cm", SensorValue[ultrasonicSensor]);
				playSound(soundBeepBeep);
			} else {
				displayCenteredTextLine(5,"No Wall Left");
			}

			sleep(400);

			MoveSensorClockwise(TARGET_DISTANCE_SENSOR);
			sleep(250);
			if (ScanForWall()) {
				displayCenteredTextLine(5,"Wall Found Forward: %d cm", SensorValue[ultrasonicSensor]);
				playSound(soundBeepBeep);
			} else {
				displayCenteredTextLine(5,"No Wall Forward");
			}
			sleep(400);

			MoveSensorClockwise(TARGET_DISTANCE_SENSOR * 2);
			sleep(250);
			if (ScanForWall()) {
				displayCenteredTextLine(5,"Wall Found Right: %d cm", SensorValue[ultrasonicSensor]);
				playSound(soundBeepBeep);
			} else {
				displayCenteredTextLine(5,"No Wall Right");
			}
			sleep(400);

			displayCenteredTextLine(5,"");
			MoveSensorDefault();
			sleep(400);
	  }
}

void MoveSensorClockwise(int target)
{
		while(nMotorEncoder[motorSensor] <= target)
		{
			motor[motorSensor] = 30;
		}

		motor[motorSensor] = 0;
}

void MoveSensorDefault()
{
		while(nMotorEncoder[motorSensor] >= 0)
		{
			motor[motorSensor] = -30;
		}

		motor[motorSensor] = 0;
}

bool ScanForWall()
{
	if (SensorValue[ultrasonicSensor] < 150)
		return true;

	return false;
}
